name: FOSSA CLI Analysis + Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#     env:
#       FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
  
      - uses: fossas/fossa-action@840373284f9ddca47e89bf82c5c7b45944fe21cc
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          project: 'something-cool-20251'

